require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '10.0'

project 'Covid',
  'Debug' => :debug,
  'Release' => :release,
  'Beta.Debug' => :debug,
  'Beta.Release' => :release

target 'Covid' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  use_unimodules!(exclude: ['expo-splash-screen'])

  # use_flipper!
  post_install do |installer|
    # flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end
end
