export { default as ConfirmSchoolScreen } from './ConfimSchoolScreen';
export { CreateNetworkGroupScreen } from './CreateNetworkGroupScreen';
export { default as JoinHigherEducationScreen } from './JoinHigherEducationScreen';
export { JoinSchoolGroupScreen } from './JoinSchoolGroupScreen';
export { default as JoinSchoolScreen } from './JoinSchoolScreen';
export { SchoolHowToScreen } from './SchoolHowToScreen';
export { SchoolIntroScreen } from './SchoolIntroScreen';
export { SchoolNetworkInfoScreen } from './SchoolNetworkInfo';
export { SchoolSuccessScreen } from './SchoolSuccessScreen';
export { SchoolGroupListScreen } from './SchoolGroupListScreen';
export { SchoolDashboardScreen } from './SchoolDashboardScreen';
