export const Services = {
  Api: Symbol('Api'),
  ContentApi: Symbol('ContentApi'),
  Content: Symbol('Content'),
  User: Symbol('User'),
  DietScore: Symbol('DietScore'),
  DietStudy: Symbol('DietStudy'),
  IncidenceHttpApi: Symbol('IncidenceHttpApi'),
  PredictiveMetricsClient: Symbol('IPredictiveMetricsClient'),
  Consent: Symbol('Consent'),
  Localisation: Symbol('Localisation'),
  Profile: Symbol('Profile'),
  Patient: Symbol('Patient'),
  CovidTest: Symbol('CovidTest'),
  SchoolService: Symbol('SchoolService'),
  Vaccine: Symbol('Vaccine'),
  VaccineApiClient: Symbol('VaccineApiClient'),
};
